MvcBookStore/MvcBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBookStore.Models;
using PagedList;
using PagedList.Mvc;


namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        // GET: BookStore
        dbQLBanSachDataContext data = new dbQLBanSachDataContext();
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);

            var sachmoi = LaySachMoi(15);
            return View(sachmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult ChuDe()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult NhaXuatBan()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult SPTheoChuDe(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
          
        }
    }
}

MvcBookStore/MvcBookStore/Views/BookStore/ChuDe.cshtml
@model IEnumerable <MvcBookStore.Models.CHUDE>
<div class="list-group">
    @foreach(var item in Model)
    {
        <a href="@Url.Action("SPTheoChuDe","BookStore", new { id=item.MaCD})" class="list-group-item">
        @item.TenChuDe
        </a>

    }
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Details.cshtml
<style type="text/css">
    #DatMua a{
        clear:both; background-color: red;
        color:white; width:120px; height:35px;
        display:block;    float:right; text-align: center;
        padding-top: 10px; text-decoration: none; font-weight:bold
    }
        #DatMua a:hover {background-color: gray;
                         color: red;

        }
</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Thông Tin  Chi Tiết Sách</h2>

<div>
    <div style="width:40%; float:left;border-left:dotted 1px;border-color:azure">
        <img src="~/HinhSanPham/@Model.Hinhminhhoa" width="100%" />
    </div>
    <div style="width:60%;float:left;padding:10px">
        <h4 style="font-weight:bold; color:red">Tên Sách :@Model.Tensach</h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mô tả:</span>@Model.Mota</p>
        <p style="font-weight:bold">Giá bán: <span style="color:red;font-size:16px">@Model.Dongia VND</span></p>
    </div>
    <div id="DatMua">
        <a href="@Url.Action("ThemGioHang","GioHang", new { @iMaSach=@Model.Masach, @strURL=Request.Url.ToString()})" class="list-group-item">
            Đặt mua
        </a>
    </div>
</div>

MvcBookStore/MvcBookStore/Views/BookStore/Index.cshtml
@using MvcBookStore.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red">Sách mới</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore", new {id= sach.Masach })">
                    <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" class="anhminhhoa" />
                    <div>
                    <h4 style="text-align:center">
                        @sach.Tensach
                    </h4>           
                    <p></p>
                    </div>
                    </a>
            </div>
        </div>
    }
    </div>
Trang@(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount;
<div class="=MenuTrang">
    @Html.PagedListPager(Model,page=>Url.Action("Index",new { page=page}))
</div>
<style>
    .Menutrang li{
        display:inline;
    }
</style>

MvcBookStore/MvcBookStore/Views/BookStore/NhaXuatBan.cshtml
@model IEnumerable<MvcBookStore.Models.NHAXUATBAN>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoNXB","BookStore", new {id = item.MaNXB})" class="list-group-item">
            @item.TenNXB
        </a>

    }
</div>

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoChuDe.cshtml
@using MvcBookStore.Models;
@model IEnumerable<MvcBookStore.Models.SACH>
@{
    ViewBag.Title = "SPTheoChuDe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red">Sách theo chủ đề</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore", new {id= sach.Masach })">
                    <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" class="anhminhhoa" />

                    <div>
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

MvcBookStore/MvcBookStore/Views/BookStore/SPTheoNXB.cshtml
@using MvcBookStore.Models;
@model IEnumerable<MvcBookStore.Models.SACH>
@{
    ViewBag.Title = "SPTheoNXB";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red">Sách theo Nhà xuất bản</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","BookStore", new {id= sach.Masach })">
                    <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" class="anhminhhoa" />

                    <div>
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                </a>
            </div>
        </div>
    }
</div>